export const SIGNALWOERTER: readonly string[] = [
  'einfach',
  'schnell',
  'clever',
  'genial',
  'ultimativ',
  'perfekt',
  'magisch',
  'kostenlos',
  'garantiert',
  'Geheimnis',
  'entdecke',
  'stopp',
  'vermeide',
  'endlich',
  'jetzt',
  'neu',
  'exklusiv',
  'bewiesen',
  'Schritt-für-Schritt',
  'in 5 Minuten',
  'ohne Aufwand',
  'wie Profis',
  'für Anfänger',
  'die beste',
  'unverzichtbar',
  'simpel',
  'effektiv',
  'lebensverändernd',
  'klappt immer',
  'nie wieder',
  'so gelingt',
  'blitzschnell',
  'ohne Vorkenntnisse',
  'garantiert erfolgreich',
  'getestet',
  'Experten-Tipp',
  'geheimer Trick',
  'sofort umsetzbar',
  'bewährte Methode',
  'einfach erklärt',
  'revolutionär',
  'erstaunlich',
  'unglaublich',
  'komplett',
  'alles was du brauchst',
  'das einzige',
  'endlich gelöst',
  'atemberaubend',
  'ausgewählte',
  'beliebte',
  'besonders',
  'beste',
  'darum lohnt sich',
  'das macht den Unterschied',
  'der beste Weg zu',
  'direkt',
  'effizient',
  'einzigartig',
  'empfehlenswert',
  'für Einsteiger',
  'für Fortgeschrittene',
  'für Profis',
  'für wenig Geld',
  'für Zuhause',
  'geeignet',
  'Geheimtipp',
  'handverlesen',
  'hilft gegen',
  'how to',
  'ideale',
  'idyllisch',
  'in nur 3 Schritten',
  'inspirierend',
  'must have',
  'noch heute',
  'optimieren',
  'organisieren',
  'praktisch',
  'Rettung',
  'Schluss mit',
  'sichtbar',
  'so vermeidest du',
  'stimmungsvoll',
  'transformierend',
  'traumhaft',
  'Tricks',
  'Tutorial',
  'ultimative',
  'meine Favoriten',
  'unvergesslich',
  'Upgrade',
  'verborgene Schätze',
  'Vergleich',
  'verschönern',
  'verwandeln',
  'vorher/nachher',
  'Vorteile von',
  'Wohlfühl-',
  'wusstest du dass',
  'Zeit sparen',
] as const

export function mergeSignalwoerter(custom: string | null | undefined): string[] {
  const standard = [...SIGNALWOERTER]
  if (!custom) return standard
  const customList = custom
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)
  return [...standard, ...customList]
}
